var ActXiv = {
    "Encounter": {
        "n": "\n",
        "t": "\t",
        "title": "Encounter",
        "duration": "13:09",
        "DURATION": "789",
        "damage": "1840349",
        "damage-m": "1.84",
        "DAMAGE-k": "1840",
        "DAMAGE-m": "2",
        "dps": "2332.51",
        "DPS": "2333",
        "DPS-k": "2",
        "encdps": "2332.51",
        "ENCDPS": "2333",
        "ENCDPS-k": "2",
        "hits": "4942",
        "crithits": "1206",
        "crithit%": "0%",
        "misses": "11",
        "hitfailed": "0",
        "swings": "4953",
        "tohit": "98.90",
        "TOHIT": "99",
        "maxhit": "Limit Break-Final Heaven-34210",
        "MAXHIT": "Limit Break-34210",
        "healed": "1810233",
        "enchps": "2294.34",
        "ENCHPS": "2294",
        "ENCHPS-k": "2",
        "critheals": "1206",
        "critheal%": "0%",
        "heals": "2771",
        "cures": "4",
        "maxheal": "Kami Kitsune-Benediction-6974",
        "MAXHEAL": "Kami Kitsune-6974",
        "maxhealward": "Kami Kitsune-Benediction-6974",
        "MAXHEALWARD": "Kami Kitsune-6974",
        "damagetaken": "1052500",
        "healstaken": "1812323",
        "powerdrain": "0",
        "powerheal": "18483",
        "kills": "10",
        "deaths": "4",
        "Last10DPS": "2095",
        "Last30DPS": "1922",
        "Last60DPS": "2347"
    },
    "Combatant": {
        "Nipah Kha\'ahk": {
            "n": "\n",
            "t": "\t",
            "name": "Nipah Kha\'ahk",
            "duration": "12:56",
            "DURATION": "776",
            "damage": "355882",
            "damage-m": "0.36",
            "DAMAGE-k": "356",
            "DAMAGE-m": "0",
            "damage%": "19%",
            "dps": "458.61",
            "DPS": "459",
            "DPS-k": "0",
            "encdps": "451.05",
            "ENCDPS": "451",
            "ENCDPS-k": "0",
            "hits": "811",
            "crithits": "200",
            "crithit%": "25%",
            "misses": "2",
            "hitfailed": "0",
            "swings": "813",
            "tohit": "99.75",
            "TOHIT": "100",
            "maxhit": "True Strike-1392",
            "MAXHIT": "1392",
            "healed": "0",
            "healed%": "0%",
            "enchps": "0.00",
            "ENCHPS": "0",
            "ENCHPS-k": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "0",
            "cures": "0",
            "maxheal": "",
            "MAXHEAL": "",
            "maxhealward": "",
            "MAXHEALWARD": "",
            "damagetaken": "100037",
            "healstaken": "146767",
            "powerdrain": "0",
            "powerheal": "0",
            "kills": "3",
            "deaths": "1",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "NAME3": "Nip",
            "NAME4": "Nipa",
            "NAME5": "Nipah",
            "NAME6": "Nipah",
            "NAME7": "Nipah K",
            "NAME8": "Nipah Kh",
            "NAME9": "Nipah Kha",
            "NAME10": "Nipah Kha\'",
            "NAME11": "Nipah Kha\'a",
            "NAME12": "Nipah Kha\'ah",
            "NAME13": "Nipah Kha\'ahk",
            "NAME14": "Nipah Kha\'ahk",
            "NAME15": "Nipah Kha\'ahk",
            "Last10DPS": "0",
            "Last30DPS": "95",
            "Last60DPS": "292",
            "Job": "Mnk",
            "ParryPct": "9%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "0%"
        },
        "Kessijiggi Wolfrun": {
            "n": "\n",
            "t": "\t",
            "name": "Kessijiggi Wolfrun",
            "duration": "13:09",
            "DURATION": "789",
            "damage": "350064",
            "damage-m": "0.35",
            "DAMAGE-k": "350",
            "DAMAGE-m": "0",
            "damage%": "19%",
            "dps": "443.68",
            "DPS": "444",
            "DPS-k": "0",
            "encdps": "443.68",
            "ENCDPS": "444",
            "ENCDPS-k": "0",
            "hits": "1240",
            "crithits": "475",
            "crithit%": "38%",
            "misses": "0",
            "hitfailed": "0",
            "swings": "1240",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Heavy Shot-1016",
            "MAXHIT": "1016",
            "healed": "2798",
            "healed%": "0%",
            "enchps": "3.55",
            "ENCHPS": "4",
            "ENCHPS-k": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "3",
            "cures": "0",
            "maxheal": "Second Wind-1005",
            "MAXHEAL": "1005",
            "maxhealward": "Second Wind-1005",
            "MAXHEALWARD": "1005",
            "damagetaken": "77145",
            "healstaken": "122216",
            "powerdrain": "0",
            "powerheal": "0",
            "kills": "1",
            "deaths": "1",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "NAME3": "Kes",
            "NAME4": "Kess",
            "NAME5": "Kessi",
            "NAME6": "Kessij",
            "NAME7": "Kessiji",
            "NAME8": "Kessijig",
            "NAME9": "Kessijigg",
            "NAME10": "Kessijiggi",
            "NAME11": "Kessijiggi",
            "NAME12": "Kessijiggi W",
            "NAME13": "Kessijiggi Wo",
            "NAME14": "Kessijiggi Wol",
            "NAME15": "Kessijiggi Wolf",
            "Last10DPS": "0",
            "Last30DPS": "293",
            "Last60DPS": "354",
            "Job": "Brd",
            "ParryPct": "50%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "34%"
        },
        "Ihm Kasukabe": {
            "n": "\n",
            "t": "\t",
            "name": "Ihm Kasukabe",
            "duration": "13:06",
            "DURATION": "786",
            "damage": "331961",
            "damage-m": "0.33",
            "DAMAGE-k": "332",
            "DAMAGE-m": "0",
            "damage%": "18%",
            "dps": "422.34",
            "DPS": "422",
            "DPS-k": "0",
            "encdps": "420.74",
            "ENCDPS": "421",
            "ENCDPS-k": "0",
            "hits": "830",
            "crithits": "141",
            "crithit%": "17%",
            "misses": "1",
            "hitfailed": "0",
            "swings": "831",
            "tohit": "99.88",
            "TOHIT": "100",
            "maxhit": "Full Thrust-2488",
            "MAXHIT": "2488",
            "healed": "11656",
            "healed%": "0%",
            "enchps": "14.77",
            "ENCHPS": "15",
            "ENCHPS-k": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "26",
            "cures": "0",
            "maxheal": "Second Wind-1108",
            "MAXHEAL": "1108",
            "maxhealward": "Second Wind-1108",
            "MAXHEALWARD": "1108",
            "damagetaken": "90082",
            "healstaken": "155129",
            "powerdrain": "0",
            "powerheal": "0",
            "kills": "2",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "NAME3": "Ihm",
            "NAME4": "Ihm",
            "NAME5": "Ihm K",
            "NAME6": "Ihm Ka",
            "NAME7": "Ihm Kas",
            "NAME8": "Ihm Kasu",
            "NAME9": "Ihm Kasuk",
            "NAME10": "Ihm Kasuka",
            "NAME11": "Ihm Kasukab",
            "NAME12": "Ihm Kasukabe",
            "NAME13": "Ihm Kasukabe",
            "NAME14": "Ihm Kasukabe",
            "NAME15": "Ihm Kasukabe",
            "Last10DPS": "0",
            "Last30DPS": "168",
            "Last60DPS": "353",
            "Job": "Drg",
            "ParryPct": "55%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "0%"
        },
        "Biggs Lightdarker": {
            "n": "\n",
            "t": "\t",
            "name": "Biggs Lightdarker",
            "duration": "13:06",
            "DURATION": "786",
            "damage": "329454",
            "damage-m": "0.33",
            "DAMAGE-k": "329",
            "DAMAGE-m": "0",
            "damage%": "17%",
            "dps": "419.15",
            "DPS": "419",
            "DPS-k": "0",
            "encdps": "417.56",
            "ENCDPS": "418",
            "ENCDPS-k": "0",
            "hits": "405",
            "crithits": "57",
            "crithit%": "14%",
            "misses": "0",
            "hitfailed": "0",
            "swings": "405",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Flare-3606",
            "MAXHIT": "3606",
            "healed": "0",
            "healed%": "0%",
            "enchps": "0.00",
            "ENCHPS": "0",
            "ENCHPS-k": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "0",
            "cures": "0",
            "maxheal": "",
            "MAXHEAL": "",
            "maxhealward": "",
            "MAXHEALWARD": "",
            "damagetaken": "87977",
            "healstaken": "139709",
            "powerdrain": "0",
            "powerheal": "4820",
            "kills": "0",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "NAME3": "Big",
            "NAME4": "Bigg",
            "NAME5": "Biggs",
            "NAME6": "Biggs",
            "NAME7": "Biggs L",
            "NAME8": "Biggs Li",
            "NAME9": "Biggs Lig",
            "NAME10": "Biggs Ligh",
            "NAME11": "Biggs Light",
            "NAME12": "Biggs Lightd",
            "NAME13": "Biggs Lightda",
            "NAME14": "Biggs Lightdar",
            "NAME15": "Biggs Lightdark",
            "Last10DPS": "0",
            "Last30DPS": "206",
            "Last60DPS": "293",
            "Job": "Blm",
            "ParryPct": "11%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "0%"
        },
        "Avenged Diver": {
            "n": "\n",
            "t": "\t",
            "name": "Avenged Diver",
            "duration": "12:57",
            "DURATION": "777",
            "damage": "221865",
            "damage-m": "0.22",
            "DAMAGE-k": "222",
            "DAMAGE-m": "0",
            "damage%": "12%",
            "dps": "285.54",
            "DPS": "286",
            "DPS-k": "0",
            "encdps": "281.20",
            "ENCDPS": "281",
            "ENCDPS-k": "0",
            "hits": "549",
            "crithits": "106",
            "crithit%": "19%",
            "misses": "0",
            "hitfailed": "0",
            "swings": "549",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Storm\'s Path-1831",
            "MAXHIT": "1831",
            "healed": "22595",
            "healed%": "1%",
            "enchps": "28.64",
            "ENCHPS": "29",
            "ENCHPS-k": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "105",
            "cures": "0",
            "maxheal": "Thrill Of Battle-1981",
            "MAXHEAL": "1981",
            "maxhealward": "Thrill Of Battle-1981",
            "MAXHEALWARD": "1981",
            "damagetaken": "241937",
            "healstaken": "307511",
            "powerdrain": "0",
            "powerheal": "0",
            "kills": "2",
            "deaths": "1",
            "threatstr": "+(0)0/-(0)2000",
            "threatdelta": "-2000",
            "NAME3": "Ave",
            "NAME4": "Aven",
            "NAME5": "Aveng",
            "NAME6": "Avenge",
            "NAME7": "Avenged",
            "NAME8": "Avenged",
            "NAME9": "Avenged D",
            "NAME10": "Avenged Di",
            "NAME11": "Avenged Div",
            "NAME12": "Avenged Dive",
            "NAME13": "Avenged Diver",
            "NAME14": "Avenged Diver",
            "NAME15": "Avenged Diver",
            "Last10DPS": "0",
            "Last30DPS": "90",
            "Last60DPS": "209",
            "Job": "War",
            "ParryPct": "11%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "0%"
        },
        "Jin Mori": {
            "n": "\n",
            "t": "\t",
            "name": "Jin Mori",
            "duration": "12:30",
            "DURATION": "750",
            "damage": "147560",
            "damage-m": "0.15",
            "DAMAGE-k": "148",
            "DAMAGE-m": "0",
            "damage%": "8%",
            "dps": "196.75",
            "DPS": "197",
            "DPS-k": "0",
            "encdps": "187.02",
            "ENCDPS": "187",
            "ENCDPS-k": "0",
            "hits": "721",
            "crithits": "132",
            "crithit%": "18%",
            "misses": "0",
            "hitfailed": "0",
            "swings": "721",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Rage Of Halone-842",
            "MAXHIT": "842",
            "healed": "10356",
            "healed%": "0%",
            "enchps": "13.13",
            "ENCHPS": "13",
            "ENCHPS-k": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "72",
            "cures": "0",
            "maxheal": "Stoneskin-947",
            "MAXHEAL": "947",
            "maxhealward": "Stoneskin-947",
            "MAXHEALWARD": "947",
            "damagetaken": "305666",
            "healstaken": "569140",
            "powerdrain": "0",
            "powerheal": "266",
            "kills": "1",
            "deaths": "1",
            "threatstr": "+(0)0/-(0)28032",
            "threatdelta": "-28032",
            "NAME3": "Jin",
            "NAME4": "Jin",
            "NAME5": "Jin M",
            "NAME6": "Jin Mo",
            "NAME7": "Jin Mor",
            "NAME8": "Jin Mori",
            "NAME9": "Jin Mori",
            "NAME10": "Jin Mori",
            "NAME11": "Jin Mori",
            "NAME12": "Jin Mori",
            "NAME13": "Jin Mori",
            "NAME14": "Jin Mori",
            "NAME15": "Jin Mori",
            "Last10DPS": "0",
            "Last30DPS": "0",
            "Last60DPS": "28",
            "Job": "Pld",
            "ParryPct": "7%",
            "BlockPct": "27%",
            "IncToHit": "100.00",
            "OverHealPct": "0%"
        },
        "Pug Lyfe": {
            "n": "\n",
            "t": "\t",
            "name": "Pug Lyfe",
            "duration": "13:21",
            "DURATION": "801",
            "damage": "67373",
            "damage-m": "0.07",
            "DAMAGE-k": "67",
            "DAMAGE-m": "0",
            "damage%": "3%",
            "dps": "84.11",
            "DPS": "84",
            "DPS-k": "0",
            "encdps": "85.39",
            "ENCDPS": "85",
            "ENCDPS-k": "0",
            "hits": "373",
            "crithits": "95",
            "crithit%": "25%",
            "misses": "7",
            "hitfailed": "0",
            "swings": "380",
            "tohit": "98.16",
            "TOHIT": "98",
            "maxhit": "Energy Drain-1048",
            "MAXHIT": "1048",
            "healed": "836767",
            "healed%": "46%",
            "enchps": "1060.54",
            "ENCHPS": "1061",
            "ENCHPS-k": "1",
            "critheals": "220",
            "critheal%": "23%",
            "heals": "968",
            "cures": "0",
            "maxheal": "Galvanize-4222",
            "MAXHEAL": "4222",
            "maxhealward": "Galvanize-4222",
            "MAXHEALWARD": "4222",
            "damagetaken": "70693",
            "healstaken": "244571",
            "powerdrain": "0",
            "powerheal": "12817",
            "kills": "0",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "NAME3": "Pug",
            "NAME4": "Pug",
            "NAME5": "Pug L",
            "NAME6": "Pug Ly",
            "NAME7": "Pug Lyf",
            "NAME8": "Pug Lyfe",
            "NAME9": "Pug Lyfe",
            "NAME10": "Pug Lyfe",
            "NAME11": "Pug Lyfe",
            "NAME12": "Pug Lyfe",
            "NAME13": "Pug Lyfe",
            "NAME14": "Pug Lyfe",
            "NAME15": "Pug Lyfe",
            "Last10DPS": "0",
            "Last30DPS": "154",
            "Last60DPS": "134",
            "Job": "Sch",
            "ParryPct": "0%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "42%"
        },
        "Limit Break": {
            "n": "\n",
            "t": "\t",
            "name": "Limit Break",
            "duration": "03:36",
            "DURATION": "216",
            "damage": "34210",
            "damage-m": "0.03",
            "DAMAGE-k": "34",
            "DAMAGE-m": "0",
            "damage%": "1%",
            "dps": "158.38",
            "DPS": "158",
            "DPS-k": "0",
            "encdps": "43.36",
            "ENCDPS": "43",
            "ENCDPS-k": "0",
            "hits": "1",
            "crithits": "0",
            "crithit%": "0%",
            "misses": "0",
            "hitfailed": "0",
            "swings": "1",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Final Heaven-34210",
            "MAXHIT": "34210",
            "healed": "0",
            "healed%": "0%",
            "enchps": "0.00",
            "ENCHPS": "0",
            "ENCHPS-k": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "0",
            "cures": "0",
            "maxheal": "",
            "MAXHEAL": "",
            "maxhealward": "",
            "MAXHEALWARD": "",
            "damagetaken": "0",
            "healstaken": "0",
            "powerdrain": "0",
            "powerheal": "0",
            "kills": "0",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "NAME3": "Lim",
            "NAME4": "Limi",
            "NAME5": "Limit",
            "NAME6": "Limit",
            "NAME7": "Limit B",
            "NAME8": "Limit Br",
            "NAME9": "Limit Bre",
            "NAME10": "Limit Brea",
            "NAME11": "Limit Break",
            "NAME12": "Limit Break",
            "NAME13": "Limit Break",
            "NAME14": "Limit Break",
            "NAME15": "Limit Break",
            "Last10DPS": "0",
            "Last30DPS": "0",
            "Last60DPS": "0",
            "Job": "",
            "ParryPct": "0%",
            "BlockPct": "0%",
            "IncToHit": "---",
            "OverHealPct": "0%"
        },
        "Kami Kitsune": {
            "n": "\n",
            "t": "\t",
            "name": "Kami Kitsune",
            "duration": "13:07",
            "DURATION": "787",
            "damage": "1980",
            "damage-m": "0.00",
            "DAMAGE-k": "2",
            "DAMAGE-m": "0",
            "damage%": "0%",
            "dps": "2.52",
            "DPS": "3",
            "DPS-k": "0",
            "encdps": "2.51",
            "ENCDPS": "3",
            "ENCDPS-k": "0",
            "hits": "12",
            "crithits": "0",
            "crithit%": "0%",
            "misses": "1",
            "hitfailed": "0",
            "swings": "13",
            "tohit": "92.31",
            "TOHIT": "92",
            "maxhit": "Stone II-745",
            "MAXHIT": "745",
            "healed": "926061",
            "healed%": "51%",
            "enchps": "1173.71",
            "ENCHPS": "1174",
            "ENCHPS-k": "1",
            "critheals": "115",
            "critheal%": "7%",
            "heals": "1597",
            "cures": "4",
            "maxheal": "Benediction-6974",
            "MAXHEAL": "6974",
            "maxhealward": "Benediction-6974",
            "MAXHEALWARD": "6974",
            "damagetaken": "78963",
            "healstaken": "127280",
            "powerdrain": "0",
            "powerheal": "580",
            "kills": "1",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "NAME3": "Kam",
            "NAME4": "Kami",
            "NAME5": "Kami",
            "NAME6": "Kami K",
            "NAME7": "Kami Ki",
            "NAME8": "Kami Kit",
            "NAME9": "Kami Kits",
            "NAME10": "Kami Kitsu",
            "NAME11": "Kami Kitsun",
            "NAME12": "Kami Kitsune",
            "NAME13": "Kami Kitsune",
            "NAME14": "Kami Kitsune",
            "NAME15": "Kami Kitsune",
            "Last10DPS": "0",
            "Last30DPS": "56",
            "Last60DPS": "31",
            "Job": "Whm",
            "ParryPct": "0%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "42%"
        }
    },
    "isActive": true
};
document.dispatchEvent(new CustomEvent('onOverlayDataUpdate', {
        detail: ActXiv
    }));
